"""empty message

Revision ID: 000a2c35eb53
Revises: 9ddd2e3c5fe3
Create Date: 2022-05-18 23:57:57.985850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000a2c35eb53'
down_revision = '9ddd2e3c5fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
