"""empty message

Revision ID: 93d24f4de95c
Revises: f00c82ba0f3b
Create Date: 2022-05-15 20:01:32.690589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d24f4de95c'
down_revision = 'f00c82ba0f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['commenter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
