"""empty message

Revision ID: 97616693741d
Revises: 1f929e3b34c3
Create Date: 2022-05-14 21:08:53.883693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97616693741d'
down_revision = '1f929e3b34c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=255), nullable=True),
    sa.Column('blog_content', sa.String(length=4000), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
