"""empty message

Revision ID: 9ddd2e3c5fe3
Revises: 5cb18414d60a
Create Date: 2022-05-17 02:57:32.942837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddd2e3c5fe3'
down_revision = '5cb18414d60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.String(length=100), nullable=False))
    op.drop_column('comments', 'comment_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_body', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
