"""empty message

Revision ID: a1c196283c98
Revises: 61e722f76950
Create Date: 2022-05-15 20:48:15.149838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c196283c98'
down_revision = '61e722f76950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['commenter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter')
    # ### end Alembic commands ###
